# https://github.com/actions/gh-actions-cache?tab=readme-ov-file
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

name: Cleanup all caches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list -R $REPO -L 100 --sort last-used --order asc | cut -f 1 )
          
          ## Setting this to not fail the workflow while deleting cache keys.
          set +e

          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R $REPO --confirm
          
          done
          echo "Done"